# Aetherium - Advanced Quantum AI Platform Configuration
# Unified configuration for all platform components

platform:
  name: "Aetherium"
  version: "1.0.0"
  description: "Advanced Quantum AI Platform - Unified Intelligence • Quantum Computing • Neuromorphic Systems • AI Productivity Suite"
  environment: "development"  # development, staging, production

# Core Platform Components
quantum:
  enabled: true
  num_qubits: 32
  backend_type: "qiskit_aer"
  time_crystal_integration: true
  quantum_error_correction: true
  optimization_engine: "hybrid"

neuromorphic:
  enabled: true
  num_neurons: 10000
  neuron_type: "lif"  # Leaky Integrate-and-Fire
  synaptic_plasticity: true
  quantum_entanglement: true
  spike_processing: "event_driven"

ai_ml:
  enabled: true
  frameworks: ["pytorch", "tensorflow", "scikit_learn"]
  models: ["transformer", "cnn", "rnn", "reinforcement"]
  quantum_ml: true
  hybrid_optimization: true

time_crystals:
  enabled: true
  num_crystals: 8
  dimensions: 3
  synchronization: true
  coherence_enhancement: true
  floquet_dynamics: true

# Platform Services
database:
  mongodb:
    enabled: true
    host: "localhost"
    port: 27017
    database: "atherium_db"
  postgresql:
    enabled: true
    host: "localhost"
    port: 5432
    database: "atherium_relational"
  redis:
    enabled: true
    host: "localhost"
    port: 6379
  vector_db:
    qdrant:
      enabled: true
      host: "localhost"
      port: 6333
    chromadb:
      enabled: true
      persist_directory: "./data/chroma"

# IoT and Communication
iot:
  mqtt:
    enabled: true
    broker: "localhost"
    port: 1883
    topics: ["atherium/quantum", "atherium/neuromorphic", "atherium/ai"]
  websocket:
    enabled: true
    port: 8001
  device_sync: true
  quantum_network: true

# Security and Authentication
security:
  jwt:
    enabled: true
    algorithm: "HS256"
    access_token_expire_minutes: 30
    refresh_token_expire_days: 7
  rbac:
    enabled: true
    roles: ["system_admin", "quantum_researcher", "neuromorphic_engineer", "ai_engineer", "data_scientist", "researcher", "user", "guest"]
  encryption:
    at_rest: true
    in_transit: true
  audit_logging: true
  rate_limiting:
    enabled: true
    requests_per_minute: 100

# Monitoring and Observability
monitoring:
  prometheus:
    enabled: true
    port: 9090
  grafana:
    enabled: true
    port: 3001
  logging:
    level: "INFO"
    format: "json"
    output: ["console", "file"]
  health_checks: true
  metrics_collection: true

# Development and Deployment
development:
  debug: true
  hot_reload: true
  test_mode: false
  mock_services: false

deployment:
  containerized: true
  orchestration: "docker_compose"
  scaling:
    auto_scaling: true
    min_replicas: 1
    max_replicas: 10
  load_balancing: true
  cdn: false

# API Configuration
api:
  version: "v1"
  base_url: "/api/v1"
  cors:
    enabled: true
    origins: ["http://localhost:3000", "http://localhost:8000"]
  rate_limiting: true
  documentation: true
  swagger_ui: true

# Frontend Configuration  
frontend:
  framework: "react"
  typescript: true
  ui_library: "antd"
  charts: "chartjs"
  real_time: true
  quantum_visualization: true
  neuromorphic_viewer: true

# Research and Development Features
research:
  quantum_algorithms: true
  neuromorphic_architectures: true
  hybrid_ai_systems: true
  time_crystal_physics: true
  brain_computer_interface: true
  distributed_quantum_networks: true

# Integration Points
integrations:
  external_apis: true
  cloud_providers: ["aws", "gcp", "azure"]
  blockchain: false
  edge_computing: true
  mobile_apps: false

# Data and Storage
data:
  backup:
    enabled: true
    frequency: "daily"
    retention_days: 30
  compression: true
  encryption: true
  versioning: true
