name: Sync Brain Plan with Knowledge Base Plan

on:
  # Run every 6 hours to check for updates
  schedule:
    - cron: '0 */6 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  sync-plans:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper changelog updates
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      
      - name: Configure git
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
      
      - name: Check for brain plan changes and sync
        env:
          BRAIN_PLAN_PATH: ${{ secrets.BRAIN_PLAN_PATH }}  # Configure this in repository secrets
        run: |
          python scripts/sync_brain_plan.py --brain-plan "${BRAIN_PLAN_PATH}" --kb-plan "plan.md"
      
      - name: Commit changes if any
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add plan.md
            git commit -m "Auto-sync brain plan with knowledge base plan"
            git push
            echo "Plan synchronized successfully"
          else
            echo "No changes to commit"
          fi
