version: '3.8'
services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
      - ./knowledge:/knowledge
      - ./resources/documentation/docs:/docs
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
